[package]
name = "coin_flip"
version = "0.1.0"
authors = ["Jack the dev"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
rand = "0.8.5"

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.2.0"